### ISSUE TITLE
编译代码过程中git库中出现大量文件处于未跟踪状态，考虑使用gitignore

### ISSUE THREAD

**Issue by ups216** [smallidea/repos#1]
如题

**Comment by ups216** [comment]
![image](https://user-images.githubusercontent.com/1203500/71256620-45a36e00-236c-11ea-9a85-b5073fb32be4.png)
补充jie截图给你。

**Comment by smallidea** [comment]
bin、obj文件因为是编译后的文件，所以我没有纳入到版本管理

**Comment by ups216** [comment]
没错，所以需要使用gitignore排除这些文件，否则会有大量不应该提交的和应该提交的文件混合在一起，容易出错误。

你需要仔细看我的issue标题和所有说明，搞清楚每个字的意思再回复！

**Comment by ups216** [comment]
![ED8E2CB1-805B-46A6-99C6-EDA6647DF316](https://user-images.githubusercontent.com/1203500/71297865-26cec700-23c0-11ea-9c4a-ee77b34c4e83.png)
如果你仔细看了我的说明，一定不会这样回复！

**Comment by ups216** [comment]
![73DC6EAF-166A-428F-B22C-418CD68B0253](https://user-images.githubusercontent.com/1203500/71297917-639abe00-23c0-11ea-8611-ed54d0a03b2f.jpeg)
如果你仔细看了我的说明一定不会这样回复！

**Comment by smallidea** [comment]
不好意思，我理解错了您的用意，您是在建议我更好的利用工具

**Comment by smallidea** [comment]
![image](https://user-images.githubusercontent.com/7962463/71307725-9333df80-242d-11ea-91e8-057b01202bf5.png)
因为我用的TortoiseSVN，所以直接在客户端做了设置

**Comment by smallidea** [comment]
我已经使用了gitignore，感觉比svn强大多了

**Comment by ups216** [comment]
good 👍
