### ISSUE TITLE
代码库中有2个DataBase.sql文件

### ISSUE THREAD

**Issue by ups216** [smallidea/repos#2]
请保留正确的文件，无用的文件一律删除。
Database 才是正确的拼写，不是DataBase

**Comment by ups216** [comment]
![image](https://user-images.githubusercontent.com/1203500/71256660-653a9680-236c-11ea-988c-21455dd77c5f.png)

**Comment by smallidea** [comment]
已删除

**Comment by ups216** [comment]
删除了哪个？为什么会遗留这些文件，考虑过对其他开发人员的影响吗？

**Comment by smallidea** [comment]
为了让交接更加简单，我移动了database.sql文件的位置，放到readme文件夹下。
之前上传的时候搞错了，没有及时的删除repos文件夹下的database.sql文件，抱歉！

**Comment by ups216** [comment]
ok 🥇
