### ISSUE TITLE
UI与我给的需求不符

### ISSUE THREAD

**Issue by ups216** [smallidea/repos#4]
2个listbox之间只有 “>>" 和 "<<" 两个按钮，而你有4个。
Sent按钮应该居中显示，不是靠左

**Comment by smallidea** [comment]
已调整

**Comment by ups216** [comment]
调整完了要贴图出来，不然我怎样知道你调整的对不对？

**Comment by smallidea** [comment]
![image](https://user-images.githubusercontent.com/7962463/71300750-c5642380-23d2-11ea-9179-ed65c749bcb0.png)

1. 只保留两个 选中后移动的按钮，去掉全部移动的两个按钮
2. sent按钮居中

**Comment by ups216** [comment]
ok
