### ISSUE TITLE
请解决你的Azure DevOps账号问题

### ISSUE THREAD

**Issue by ups216** [smallidea/repos#5]
我们最终仍然需要使用Azure DevOps完成这个测试，使用github只是暂时的。

**Comment by smallidea** [comment]
![image](https://user-images.githubusercontent.com/7962463/71307833-04c05d80-242f-11ea-82a2-1e2f44018290.png)
我尝试在Azure DevOps中邀请了您，您看看是否可以收到
我的账号是：jianba23@outlook.com

**Comment by ups216** [comment]
你仔细看一下我的邮件地址是什么？

**Comment by ups216** [comment]
![image](https://user-images.githubusercontent.com/1203500/71319271-e4e47480-24d6-11ea-85de-412ede952875.png)
我给你的jianba23@outlook.com发送了邀请

**Comment by ups216** [comment]
![image](https://user-images.githubusercontent.com/1203500/71319299-46a4de80-24d7-11ea-9dea-7fd50397e4d0.png)

你再检查一下邮箱

**Comment by smallidea** [comment]
我已经迁移到Azure DevOps

**Comment by ups216** [comment]
![F09B838B-1556-4CBA-8634-DB9CF8507BF9](https://user-images.githubusercontent.com/1203500/71450887-f2874c00-27ad-11ea-96cc-8d8ab2c38fa0.png)
![C73017AC-A719-467C-BD0B-5974054817B3](https://user-images.githubusercontent.com/1203500/71450888-f2874c00-27ad-11ea-834c-d2160bf02140.png)


请在迁移的时候保持历史记录！

**Comment by ups216** [comment]
我们后续在Azure DevOps中继续，这里可以关闭了。
