### ISSUE TITLE
Readme.md在我本地显示为乱码，请注意正确的encoding

### ISSUE THREAD

**Issue by ups216** [smallidea/repos#6]
![image](https://user-images.githubusercontent.com/1203500/71257301-57861080-236e-11ea-8734-ea8a16e00600.png)

**Comment by smallidea** [comment]
已经修改为UTF-8

**Comment by ups216** [comment]
改了以后你测试过其他系统能够正常打开吗？贴图上来

**Comment by smallidea** [comment]
![image](https://user-images.githubusercontent.com/7962463/71300694-440c9100-23d2-11ea-96b4-f89b3b11c3a3.png)

我把文件使用utf-8格式保存就不会中文乱码了

**Comment by ups216** [comment]
good 👍 
但是，你把readme.md放到文件夹里面以后github的页面就无法自动显示readme内容了，所以还是需要放在root目录。

![image](https://user-images.githubusercontent.com/1203500/71319105-a3eb6080-24d4-11ea-9461-3e588bacdb62.png)

**Comment by smallidea** [comment]
已经调整了路径

**Comment by smallidea** [comment]
![image](https://user-images.githubusercontent.com/7962463/71403323-543e9d80-266a-11ea-8b4d-0c6c542b19d5.png)

已经调整了路径

**Comment by ups216** [comment]
OK
